import "./globals.scss";
import {Quicksand} from "next/font/google";

const quicksand = Quicksand({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className={quicksand.className}>
      <body>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
